package CodeReview.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_ReviewStatus extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ReviewStatus() {
    super(0xc126621b8cee42a4L, 0x8eb8ffdf4b0da36aL, 0x72dc9a49a09624efL, "ReviewStatus", "r:ec5757ac-2df5-4581-8b80-8695121b0b07(CodeReview.structure)/8276659856217613551", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_InProgress_0 = new EnumerationDescriptor.MemberDescriptor("In Progress", "In Progress", "r:ec5757ac-2df5-4581-8b80-8695121b0b07(CodeReview.structure)/8276659856217613552", "In Progress");
  private final EnumerationDescriptor.MemberDescriptor VALUE_ForReview_0 = new EnumerationDescriptor.MemberDescriptor("For Review", "For Review", "r:ec5757ac-2df5-4581-8b80-8695121b0b07(CodeReview.structure)/8276659856217613553", "For Review");
  private final EnumerationDescriptor.MemberDescriptor VALUE_Accepted_0 = new EnumerationDescriptor.MemberDescriptor("Accepted", "Accepted", "r:ec5757ac-2df5-4581-8b80-8695121b0b07(CodeReview.structure)/8276659856217613556", "Accepted");
  private final EnumerationDescriptor.MemberDescriptor VALUE_Rejected_0 = new EnumerationDescriptor.MemberDescriptor("Rejected", "Rejected", "r:ec5757ac-2df5-4581-8b80-8695121b0b07(CodeReview.structure)/8276659856217613560", "Rejected");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_InProgress_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_InProgress_0, VALUE_ForReview_0, VALUE_Accepted_0, VALUE_Rejected_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "In Progress":
        return VALUE_InProgress_0;
      case "For Review":
        return VALUE_ForReview_0;
      case "Accepted":
        return VALUE_Accepted_0;
      case "Rejected":
        return VALUE_Rejected_0;
    }
    return null;
  }
}
