package CodeReview.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCodeReview = createDescriptorForCodeReview();
  /*package*/ final ConceptDescriptor myConceptStatusChange = createDescriptorForStatusChange();
  /*package*/ final EnumerationDescriptor myEnumerationReviewStatus = new EnumerationDescriptor_ReviewStatus();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.aggregatedLanguage(0xc7fb639fbe784307L, 0x89b0b5959c3fa8c8L, "jetbrains.mps.lang.text");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCodeReview, myConceptStatusChange);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.CodeReview:
        return myConceptCodeReview;
      case LanguageConceptSwitch.StatusChange:
        return myConceptStatusChange;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationReviewStatus);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCodeReview() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeReview", "CodeReview", 0xc126621b8cee42a4L, 0x8eb8ffdf4b0da36aL, 0x72dc9a49a0951f1eL);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.core.structure.NodeAttribute", 0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da54L);
    b.origin("r:ec5757ac-2df5-4581-8b80-8695121b0b07(CodeReview.structure)/8276659856217546526");
    b.version(2);
    b.aggregate("changes", 0x72dc9a49a0962551L).target(0xc126621b8cee42a4L, 0x8eb8ffdf4b0da36aL, 0x72dc9a49a09624eeL).optional(true).ordered(true).multiple(true).origin("8276659856217613649").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStatusChange() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CodeReview", "StatusChange", 0xc126621b8cee42a4L, 0x8eb8ffdf4b0da36aL, 0x72dc9a49a09624eeL);
    b.class_(false, false, false);
    b.origin("r:ec5757ac-2df5-4581-8b80-8695121b0b07(CodeReview.structure)/8276659856217613550");
    b.version(2);
    b.property("status", 0x72dc9a49a09624fdL).type(MetaIdFactory.dataTypeId(0xc126621b8cee42a4L, 0x8eb8ffdf4b0da36aL, 0x72dc9a49a09624efL)).origin("8276659856217613565").done();
    b.property("author", 0x72dc9a49a096252dL).type(PrimitiveTypeId.STRING).origin("8276659856217613613").done();
    b.aggregate("comment", 0x72dc9a49a09624ffL).target(0xc7fb639fbe784307L, 0x89b0b5959c3fa8c8L, 0x2331694e5619f411L).optional(true).ordered(true).multiple(false).origin("8276659856217613567").done();
    return b.create();
  }
}
