package CodeReviewPlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.BaseKeymapChanges;

public final class CodeReviewKeys_KeymapChanges extends BaseKeymapChanges {
  public CodeReviewKeys_KeymapChanges() {
    add("CodeReviewPlugin.plugin.HideCodeReviews_Action", "ctrl alt shift C");
    add("CodeReviewPlugin.plugin.ShowCodeReviews_Action", "ctrl alt shift C");
  }
  @Override
  public String getScheme() {
    return "$default";
  }

}
