package CodeReviewPlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.BaseKeymapChanges;
import com.intellij.openapi.actionSystem.Shortcut;
import com.intellij.openapi.actionSystem.KeyboardShortcut;
import javax.swing.KeyStroke;

public class CodeReviewKeys_KeymapChanges extends BaseKeymapChanges {
  public CodeReviewKeys_KeymapChanges() {
    // simple
    addSimpleShortcut("CodeReviewPlugin.plugin.HideCodeReviews_Action", getShortcut("ctrl alt shift C"));
    addSimpleShortcut("CodeReviewPlugin.plugin.ShowCodeReviews_Action", getShortcut("ctrl alt shift C"));
    // simple parameterized
    // complex
  }
  public String getScheme() {
    return "$default";
  }
  public static Shortcut getShortcut(String stroke) {
    return new KeyboardShortcut(KeyStroke.getKeyStroke(stroke), null);
  }
}
