package CodeReviewPlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class CodeReviewActions_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "CodeReviewPlugin.plugin.CodeReviewActions_ActionGroup";

  public CodeReviewActions_ActionGroup(@Nullable ApplicationPlugin plugin) {
    super("CodeReviewActions", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    CodeReviewActions_ActionGroup.this.addAction("CodeReviewPlugin.plugin.ShowCodeReviews_Action");
    CodeReviewActions_ActionGroup.this.addAction("CodeReviewPlugin.plugin.HideCodeReviews_Action");
  }
}
