package CodeReviewPlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;

public class CodeReviewActions_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "CodeReviewPlugin.plugin.CodeReviewActions_ActionGroup";
  public CodeReviewActions_ActionGroup() {
    super("CodeReviewActions", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    CodeReviewActions_ActionGroup.this.addAction("CodeReviewPlugin.plugin.ShowCodeReviews_Action");
    CodeReviewActions_ActionGroup.this.addAction("CodeReviewPlugin.plugin.HideCodeReviews_Action");
  }
}
