package CodeReviewPlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.BaseKeymapChanges;

public final class MacOSX105_KeymapChanges extends BaseKeymapChanges {
  public MacOSX105_KeymapChanges() {
    replace("CodeReviewPlugin.plugin.HideCodeReviews_Action", "ctrl alt shift C");
    replace("CodeReviewPlugin.plugin.ShowCodeReviews_Action", "ctrl alt shift C");
  }
  @Override
  public String getScheme() {
    return "Mac OS X 10.5+";
  }

}
