package CodeReview.sandbox;

/*Generated by MPS */


public class Sample {
  public static void main(String[] args) {
    System.out.println("Hello");
    System.out.println("Foo");
    System.out.println("Bar");
  }
}
